[theme]
primaryColor = "#2ea44f"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f7f7f8"
textColor = "#0d1117"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false

[ui]
hideTopBar = false
hideSidebarNav = true

[client]
showErrorDetails = true
toolbarMode = "minimal"

[runner]
fastReruns = true
